name: Build

on:
  push:
    branches: [main, initial]
  pull_request:
    branches: [main, initial]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build distribution

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload dist to artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dist
          path: dist/
          retention-days: 7
